sonar.host.url=https://sonarcloud.io

sonar.projectKey=aidatleuliyeva-hub_parcel-locker-management-system
sonar.organization=aidatleuliyeva-hub

sonar.projectName=Parcel Locker Management System
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=src/main/java/com/example/parcellocker/Main.java,src/main/java/com/example/parcellocker/ui/**,src/main/java/com/example/parcellocker/application/dto/**,src/main/java/com/example/parcellocker/persistence/JpaUtil.java